services:
  database:
    image: postgres:16-.alpine3.18
    environment:
      POSTGRES_PASSWORD: "local_password"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
