services:
  database:
    image: postgres:16-.alpine3.18
    env_file:
      - ../env.development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
